from typing import Optional

from sqlalchemy import MetaData, Table, Column, Integer
from sqlalchemy.dialects import postgresql

from tests.schemas import KEYWORD_SCHEMA_NAME
from tests.base.run_migration_test_abc import CompareAndRunTestCase


class TestExoticSchemaNameRender(CompareAndRunTestCase):
    """https://github.com/Pogchamp-company/alembic-postgresql-enum/issues/95#issuecomment-2619738045"""

    old_variants = ("Walter White", "Jesse Pinkman", "Tuco")
    new_variants = ("Walter White", "Jesse Pinkman")
    enum_name = "dealers"

    def get_database_schema(self) -> MetaData:
        metadata = MetaData()
        Table(
            "pricing",
            metadata,
            Column("id", Integer, primary_key=True),
            Column(
                "dealer",
                postgresql.ENUM(*self.old_variants, name=self.enum_name, schema=KEYWORD_SCHEMA_NAME),
            ),
            schema=KEYWORD_SCHEMA_NAME,
        )

        return metadata

    def get_target_schema(self) -> MetaData:
        metadata = MetaData()
        Table(
            "pricing",
            metadata,
            Column("id", Integer, primary_key=True),
            Column(
                "dealer",
                postgresql.ENUM(*self.new_variants, name=self.enum_name, schema=KEYWORD_SCHEMA_NAME),
            ),
            schema=KEYWORD_SCHEMA_NAME,
        )

        return metadata

    def get_expected_upgrade(self) -> str:
        return f"""
            # ### commands auto generated by Alembic - please adjust! ###
            op.sync_enum_values(
                enum_schema='default',
                enum_name='dealers',
                new_values=['Walter White', 'Jesse Pinkman'],
                affected_columns=[TableReference(table_schema='default', table_name='pricing', column_name='dealer')],
                enum_values_to_rename=[],
            )
            # ### end Alembic commands ###
        """

    def get_expected_downgrade(self) -> Optional[str]:
        return f"""
            # ### commands auto generated by Alembic - please adjust! ###
            op.sync_enum_values(
                enum_schema='default',
                enum_name='dealers',
                new_values=['Walter White', 'Jesse Pinkman', 'Tuco'],
                affected_columns=[TableReference(table_schema='default', table_name='pricing', column_name='dealer')],
                enum_values_to_rename=[],
            )
            # ### end Alembic commands ###
        """
